name: Riku build

on: push

jobs:
  riku-build:
    name: Riku Frontend Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: NPM install
        run: npm install
        
      - name: NPM build
        run: npm run build
        
      - name: test
        run: ls
